[build]
  command = "bun run sync && bun run check && bun run build"
  publish = "./build/"
  [build.environment]
    NODE_VERSION = "20.14.0"
    NPM_VERSION = "10.8.1"
[[headers]]
  for = "/_app/immutable/*"
  [headers.values]
    cache-control = "immutable, max-age=31536000, public, s-maxage=31536000"